In [2]:
import pandas as pd
import numpy as np

### lets work on 6_6 first

In [2]:
##
pd_6_6_v100 = pd.read_csv('../../data/submissions/test_v6_6_loss/stage_1.csv')
pd_6_6_p100 = pd.read_csv('../../data/str_kag_2/stage_1_6_6.csv')

In [3]:
pd_6_6_v100.head(3)

ID  count  \
0  0040581b-f1f2-4fbe-b043-b6bfea5404bb      1   
1  0040581b-f1f2-4fbe-b043-b6bfea5404bb      2   
2  0040581b-f1f2-4fbe-b043-b6bfea5404bb      3   

                                            encoding         0         1  \
0  eNqtVm2PojAQ/ksMZe+Sy21yubtc4gKDIkpBUJQ3KyD//9...  0.336334  0.033897   
1  eNrVUm1PwkAM/kvt3XgRjEajvO7uhGCEEHCgcSQi/v9vXt...  0.110140  0.016685   
2  eNoLCEgJMg4wDMg3NPQ39Df2NfaF0EZ+IBoBIXzc8oSgAR...  0.411060  0.045896   

          2         3         4         5         6  ...         9        10  \
0  0.301812  0.447226  0.090477  0.169021  0.145265  ...  0.124362  0.060528   
1  0.488759  0.466848  0.033412  0.026571  0.235993  ...  0.157504  0.025630   
2  0.503939  0.271923  0.154735  0.150925  0.119339  ...  0.141826  0.034614   

         11        12        13        14        15        16        17  \
0  0.065688  0.185014  0.170284  0.084668  0.060342  0.435709  0.336736   
1  0.019908  0.107970  0.123429  0.112150  0.051560  0.498646  0.257160   
2  0.052269  0.156636  0.146763  0.067964  0.114447  0.342994  0.394549   

         18  
0  0.088017  
1  0.009427  
2  0.054016  

[3 rows x 22 columns]

In [4]:
pd_6_6_p100.head(3)

ID  count  \
0  02861579-97fb-4482-a613-356e0bf5d090      1   
1  02861579-97fb-4482-a613-356e0bf5d090      2   
2  02861579-97fb-4482-a613-356e0bf5d090      3   

                                            encoding         0         1  \
0  eNq12Ol228gRBtBXYhEE5GRmnEzmeMYAySL2nViIfX//f6...  0.756969  0.150225   
1  eNqtVNmSqkgQ/SUSC6WNGxMz09PSDZKAC8i+F6Ci//82lS...  0.720771  0.042627   
2  eNqVVn17ojAM/0oNuInDu3vupuJUAsJkY6DTwTzfkO//3y...  0.795245  0.054924   

          2         3         4         5         6  ...         9        10  \
0  0.074002  0.081757  0.030632  0.092248  0.330049  ...  0.038876  0.229152   
1  0.056232  0.072030  0.055167  0.096245  0.177644  ...  0.044284  0.358046   
2  0.064855  0.054077  0.028469  0.096710  0.274223  ...  0.050017  0.190109   

         11        12        13        14        15        16        17  \
0  0.137229  0.112763  0.050166  0.154057  0.031010  0.425211  0.201852   
1  0.198756  0.199114  0.079672  0.044123  0.027741  0.502750  0.153113   
2  0.102981  0.099474  0.055067  0.086317  0.023467  0.420885  0.319187   

         18  
0  0.028822  
1  0.024135  
2  0.009223  

[3 rows x 22 columns]

In [5]:
### lets extract the unique token from p100
p100_unique_val = pd_6_6_p100['ID'].unique()

pd_6_6_v100_filtered = pd_6_6_v100[pd_6_6_v100['ID'].isin(p100_unique_val)]

In [6]:
print(pd_6_6_v100_filtered.shape, pd_6_6_p100.shape)

(9868, 22) (9868, 22)


In [7]:
pd_6_6_v100_filtered.head(5)

ID  count  \
217  02861579-97fb-4482-a613-356e0bf5d090      1   
218  02861579-97fb-4482-a613-356e0bf5d090      2   
219  02861579-97fb-4482-a613-356e0bf5d090      3   
220  02861579-97fb-4482-a613-356e0bf5d090      4   
221  02861579-97fb-4482-a613-356e0bf5d090      5   

                                              encoding         0         1  \
217  eNq12Ol228gRBtBXYpEE5GRmnEzmeMYAycK+g1iIfX//f6...  0.754483  0.127106   
218  eNqtVNmSqkgQ/SUSC6WNGxMz09PSDZKAC8i+F6Ci//82lS...  0.710326  0.044746   
219  eNqVVn17ojAM/0oNuInDu3vupuJUAsJkY6DTwTzfkO//3y...  0.784326  0.055428   
220  eNp1VG1zojAQ/kvZBL3a9ua80bF3FXZtRSoQQQWkqG3//7...  0.825000  0.043875   
221  eNptVG2TmjAQ/ktZ3uRap+2McwVRlhNQMAh4YACr4v//1m...  0.603999  0.189712   

            2         3         4         5         6  ...         9  \
217  0.074637  0.080416  0.034525  0.115932  0.329144  ...  0.037676   
218  0.058104  0.071665  0.058592  0.099247  0.183146  ...  0.043941   
219  0.063754  0.051896  0.030660  0.105663  0.279695  ...  0.052709   
220  0.029842  0.033416  0.030743  0.090101  0.230912  ...  0.051613   
221  0.121261  0.167011  0.099875  0.146378  0.188741  ...  0.052373   

           10        11        12        13        14        15        16  \
217  0.207956  0.128064  0.113851  0.049902  0.151036  0.032665  0.440464   
218  0.370971  0.196121  0.205278  0.074006  0.045804  0.028272  0.493293   
219  0.200375  0.096160  0.098165  0.057252  0.091030  0.025655  0.422079   
220  0.161634  0.104679  0.115237  0.054698  0.149033  0.040715  0.431538   
221  0.236309  0.241617  0.603443  0.062603  0.045529  0.037449  0.529164   

           17        18  
217  0.193190  0.028302  
218  0.151527  0.023123  
219  0.318027  0.010208  
220  0.235098  0.015093  
221  0.092180  0.039947  

[5 rows x 22 columns]

In [8]:
pd_6_6_p100.head(5)

ID  count  \
0  02861579-97fb-4482-a613-356e0bf5d090      1   
1  02861579-97fb-4482-a613-356e0bf5d090      2   
2  02861579-97fb-4482-a613-356e0bf5d090      3   
3  02861579-97fb-4482-a613-356e0bf5d090      4   
4  02861579-97fb-4482-a613-356e0bf5d090      5   

                                            encoding         0         1  \
0  eNq12Ol228gRBtBXYhEE5GRmnEzmeMYAySL2nViIfX//f6...  0.756969  0.150225   
1  eNqtVNmSqkgQ/SUSC6WNGxMz09PSDZKAC8i+F6Ci//82lS...  0.720771  0.042627   
2  eNqVVn17ojAM/0oNuInDu3vupuJUAsJkY6DTwTzfkO//3y...  0.795245  0.054924   
3  eNp1VH97ojAM/kpNi9657Z7zHnfubkKiU5lABRWQoWz7/v...  0.831011  0.043805   
4  eNptVG2TmjAQ/ktZ3uRap+2McwVRlhNQMAh4YACr4v//1m...  0.607552  0.193843   

          2         3         4         5         6  ...         9        10  \
0  0.074002  0.081757  0.030632  0.092248  0.330049  ...  0.038876  0.229152   
1  0.056232  0.072030  0.055167  0.096245  0.177644  ...  0.044284  0.358046   
2  0.064855  0.054077  0.028469  0.096710  0.274223  ...  0.050017  0.190109   
3  0.029151  0.034753  0.028053  0.086620  0.229341  ...  0.052024  0.150549   
4  0.130714  0.170735  0.100617  0.146463  0.189942  ...  0.053950  0.226419   

         11        12        13        14        15        16        17  \
0  0.137229  0.112763  0.050166  0.154057  0.031010  0.425211  0.201852   
1  0.198756  0.199114  0.079672  0.044123  0.027741  0.502750  0.153113   
2  0.102981  0.099474  0.055067  0.086317  0.023467  0.420885  0.319187   
3  0.105795  0.115165  0.053893  0.143483  0.038605  0.432421  0.229197   
4  0.247957  0.612019  0.067948  0.046503  0.040262  0.537237  0.090428   

         18  
0  0.028822  
1  0.024135  
2  0.009223  
3  0.015266  
4  0.042763  

[5 rows x 22 columns]

In [9]:
lets_different = pd_6_6_v100_filtered[[str(i) for i in range(19)]].values - pd_6_6_p100[[str(i) for i in range(19)]].values

In [10]:
lets_different.shape

(9868, 19)

In [11]:
mean_6_6 = lets_different.mean(0)
mean_6_6.shape

(19,)

In [18]:
mean_6_6

array([ 9.29849161e-05,  7.17469789e-04, -3.59509372e-03, -4.39483462e-03,
       -1.81291516e-03,  2.14755661e-03, -9.69174490e-04, -4.12395415e-03,
       -5.51596648e-04,  1.78043239e-03, -3.66965946e-03, -1.01453032e-02,
       -2.08877523e-03, -1.96720680e-02, -1.15437992e-04,  2.38051006e-03,
       -8.19688687e-03,  1.10217377e-02, -9.21556908e-04])

In [13]:
pd_6_6_p100[[str(i) for i in range(19)]].values + mean_6_6

array([[0.7570619 , 0.15094272, 0.07040738, ..., 0.41701439, 0.21287415,
        0.02790018],
       [0.72086418, 0.04334435, 0.05263735, ..., 0.49455303, 0.16413454,
        0.02321312],
       [0.79533786, 0.05564135, 0.06125983, ..., 0.41268817, 0.33020825,
        0.00830127],
       ...,
       [0.10130461, 0.02886908, 0.05368156, ..., 0.40835411, 0.42732347,
        0.03274193],
       [0.0465651 , 0.0150799 , 0.05064083, ..., 0.43657005, 0.69171131,
        0.02275008],
       [0.09045535, 0.03360247, 0.14371001, ..., 0.41737691, 0.53549463,
        0.054752  ]])

## lets work on 6_6_2

In [16]:
pd_6_6_2_v100 = pd.read_csv('../../data/submissions/test_v6_6_2_loss/stage_1.csv')
pd_6_6_2_p100 = pd.read_csv('../../data/str_kag_2/stage_1_6_6_2.csv')
p100_unique_val = pd_6_6_2_p100['ID'].unique()

pd_6_6_2_v100_filtered = pd_6_6_2_v100[pd_6_6_2_v100['ID'].isin(p100_unique_val)]
print(pd_6_6_2_v100_filtered.shape, pd_6_6_2_p100.shape)
lets_different = pd_6_6_2_v100_filtered[[str(i) for i in range(19)]].values - pd_6_6_2_p100[[str(i) for i in range(19)]].values
mean_6_6_2 = lets_different.mean(0)
print(mean_6_6_2.shape)
mean_6_6_2

(9868, 22) (9868, 22)
(19,)


array([ 0.00912525, -0.00019775, -0.00510275, -0.01552011, -0.00997425,
       -0.00478028, -0.00419081, -0.00618159, -0.00667691, -0.00569972,
       -0.01607459, -0.0108702 , -0.00681728, -0.00707488, -0.01076032,
       -0.00288307,  0.00618556, -0.01145433, -0.0055709 ])

## lets work on 6_6_3

In [17]:
pd_6_6_3_v100 = pd.read_csv('../../data/submissions/test_v6_6_3_loss/stage_1.csv')
pd_6_6_3_p100 = pd.read_csv('../../data/str_kag_2/stage_1_6_6_3.csv')
p100_unique_val = pd_6_6_3_p100['ID'].unique()

pd_6_6_3_v100_filtered = pd_6_6_3_v100[pd_6_6_3_v100['ID'].isin(p100_unique_val)]
print(pd_6_6_3_v100_filtered.shape, pd_6_6_3_p100.shape)
lets_different = pd_6_6_3_v100_filtered[[str(i) for i in range(19)]].values - pd_6_6_3_p100[[str(i) for i in range(19)]].values
mean_6_6_3 = lets_different.mean(0)
print(mean_6_6_3.shape)
mean_6_6_3

(9868, 22) (9868, 22)
(19,)


array([0.07072176, 0.11267665, 0.14429368, 0.12940642, 0.10606747,
       0.16546211, 0.14309853, 0.14479114, 0.16269307, 0.14846139,
       0.1243546 , 0.16770698, 0.16495702, 0.1009928 , 0.11299006,
       0.12483789, 0.13798061, 0.1206634 , 0.13405712])

# lets work on 6_6_3_1

In [3]:
pd_6_6_3_v100 = pd.read_csv('../../data/submissions/test_v6_6_3_1_loss/stage_1.csv')
pd_6_6_3_p100 = pd.read_csv('../../data/str_kag_2/stage_1_6_6_3_1.csv')
p100_unique_val = pd_6_6_3_p100['ID'].unique()

pd_6_6_3_v100_filtered = pd_6_6_3_v100[pd_6_6_3_v100['ID'].isin(p100_unique_val)]
print(pd_6_6_3_v100_filtered.shape, pd_6_6_3_p100.shape)
lets_different = pd_6_6_3_v100_filtered[[str(i) for i in range(19)]].values - pd_6_6_3_p100[[str(i) for i in range(19)]].values
mean_6_6_3 = lets_different.mean(0)
print(mean_6_6_3.shape)
mean_6_6_3

(8368, 22) (8368, 22)
(19,)


array([ 0.01585845,  0.00545589,  0.0043787 ,  0.00468656,  0.0055035 ,
        0.00576125,  0.00237679, -0.00280384,  0.00534345,  0.00288881,
        0.0066975 ,  0.00478291,  0.0060642 , -0.00101075,  0.00315787,
        0.00217736,  0.00567489, -0.01409792,  0.00140922])

# lets work on 6_6_3_2_2

In [8]:
pd_6_6_3_v100 = pd.read_csv('../../data/submissions/test_v6_6_3_2_2_loss/stage_1.csv')
pd_6_6_3_p100 = pd.read_csv('../../data/str_kag_2/stage_1_6_6_3_2_2.csv')
p100_unique_val = pd_6_6_3_p100['ID'].unique()

pd_6_6_3_v100_filtered = pd_6_6_3_v100[pd_6_6_3_v100['ID'].isin(p100_unique_val)]
print(pd_6_6_3_v100_filtered.shape, pd_6_6_3_p100.shape)
lets_different = pd_6_6_3_v100_filtered[[str(i) for i in range(19)]].values - pd_6_6_3_p100[[str(i) for i in range(19)]].values
mean_6_6_3 = lets_different.mean(0)
print(mean_6_6_3.shape)
mean_6_6_3

(9868, 22) (9868, 22)
(19,)


array([ 0.00494488, -0.00247027,  0.00081842,  0.00157168,  0.00404206,
        0.00311271, -0.00840997, -0.00035653, -0.00295877,  0.00129175,
       -0.00472525, -0.00162622, -0.00197336, -0.00029515, -0.00033818,
        0.00266456, -0.01182517,  0.00555528,  0.003978  ])

## lets work on 6_6_3_2_2_1

In [11]:
pd_6_6_3_v100 = pd.read_csv('../../data/submissions/test_v6_6_3_2_2_1_loss/stage_1.csv')
pd_6_6_3_p100 = pd.read_csv('../../data/str_kag_2/stage_1_6_6_3_2_2_1.csv')
p100_unique_val = pd_6_6_3_p100['ID'].unique()

pd_6_6_3_v100_filtered = pd_6_6_3_v100[pd_6_6_3_v100['ID'].isin(p100_unique_val)]
print(pd_6_6_3_v100_filtered.shape, pd_6_6_3_p100.shape)
lets_different = pd_6_6_3_v100_filtered[[str(i) for i in range(19)]].values - pd_6_6_3_p100[[str(i) for i in range(19)]].values
mean_6_6_3 = lets_different.mean(0)
print(mean_6_6_3.shape)
mean_6_6_3

(9868, 22) (9868, 22)
(19,)


array([ 5.90629263e-03,  2.36834468e-03,  1.01321792e-03,  2.90205727e-04,
        8.45231281e-04,  9.80369698e-05,  3.71625599e-03,  1.92525899e-03,
        3.24993138e-03,  9.86899284e-04,  3.85914562e-03,  2.98988327e-03,
        1.56832405e-03, -3.65031145e-03,  2.81727139e-03,  3.24837389e-04,
        5.12416630e-03, -8.27996925e-04, -1.86996343e-03])

## lets work on 6_6_3_2_2_2

In [10]:
pd_6_6_3_v100 = pd.read_csv('../../data/submissions/test_v6_6_3_2_2_2_loss/stage_1.csv')
pd_6_6_3_p100 = pd.read_csv('../../data/str_kag_2/stage_1_6_6_3_2_2_2.csv')
p100_unique_val = pd_6_6_3_p100['ID'].unique()

pd_6_6_3_v100_filtered = pd_6_6_3_v100[pd_6_6_3_v100['ID'].isin(p100_unique_val)]
print(pd_6_6_3_v100_filtered.shape, pd_6_6_3_p100.shape)
lets_different = pd_6_6_3_v100_filtered[[str(i) for i in range(19)]].values - pd_6_6_3_p100[[str(i) for i in range(19)]].values
mean_6_6_3 = lets_different.mean(0)
print(mean_6_6_3.shape)
mean_6_6_3

(9868, 22) (9868, 22)
(19,)


array([ 0.00610256,  0.00180529,  0.00386388,  0.00179933,  0.00218721,
        0.00428756, -0.00456166, -0.00114968, -0.00150308, -0.00296846,
       -0.00096942,  0.00596385, -0.00214865, -0.00217443,  0.00284134,
        0.001995  , -0.01012879, -0.00611884,  0.01226108])

## learning rate chekcing 

In [26]:
!pip install git+https://github.com/ildoonet/pytorch-gradual-warmup-lr.git

  Cloning https://github.com/ildoonet/pytorch-gradual-warmup-lr.git to /tmp/pip-req-build-ybn6y8dv
  Running command git clone -q https://github.com/ildoonet/pytorch-gradual-warmup-lr.git /tmp/pip-req-build-ybn6y8dv
  Created wheel for warmup-scheduler: filename=warmup_scheduler-0.3.2-py3-none-any.whl size=3881 sha256=fa8e652f20ed9c6755820969f04a31425272ed77a8f7a7911a2dfb27d2c119db
  Stored in directory: /tmp/pip-ephem-wheel-cache-xgti4dtb/wheels/f5/e5/14/0d10ec4477507fbad192d8837535e6f2d41a287cb03aa2b7ea
Successfully built warmup-scheduler
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.


In [47]:
import torch
from torch.optim.lr_scheduler import StepLR, ExponentialLR, CosineAnnealingLR
from torch.optim.sgd import SGD
from torch import optim

from warmup_scheduler import GradualWarmupScheduler


if __name__ == '__main__':
    model = [torch.nn.Parameter(torch.randn(2, 2, requires_grad=True))]
    optimizer = SGD(model, 0.1)

    # scheduler_warmup is chained with schduler_steplr
    scheduler_cosine = CosineAnnealingLR(optimizer, T_max=10)
    scheduler = GradualWarmupScheduler(optimizer, multiplier=1, total_epoch=5, after_scheduler=scheduler_cosine)
    #scheduler_warmup = GradualWarmupScheduler(optim, multiplier=1, total_epoch=5, after_scheduler=scheduler_steplr)

    # this zero gradient update is needed to avoid a warning message, issue #8.
    optimizer.zero_grad()
    #optimizer.step()

    for epoch in range(1, 20):
        scheduler_warmup.step(epoch)
        print(epoch, optimizer.param_groups[0]['lr'])

        #optimizer.step()  

1 0.020000000000000004
2 0.04000000000000001
3 0.06
4 0.08000000000000002
5 0.1
6 0.1
7 0.09045084971874738
8 0.07938926261462366
9 0.06545084971874737
10 0.05
11 0.03454915028125263
12 0.02061073738537635
13 0.009549150281252633
14 0.0024471741852423235
15 0.0
16 0.0024471741852423127
17 0.009549150281252623
18 0.02061073738537634
19 0.034549150281252626


/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)


In [42]:
import torch
from torch.optim.lr_scheduler import StepLR, ExponentialLR, CosineAnnealingLR
from torch.optim.sgd import SGD

from warmup_scheduler import GradualWarmupScheduler


if __name__ == '__main__':
    model = [torch.nn.Parameter(torch.randn(2, 2, requires_grad=True))]
    optim = SGD(model, 0.1)

    # scheduler_warmup is chained with schduler_steplr
    scheduler_steplr = CosineAnnealingLR(optim,T_max = 10)
    scheduler_warmup = GradualWarmupScheduler(optim, multiplier=1, total_epoch=5, after_scheduler=scheduler_steplr)

    # this zero gradient update is needed to avoid a warning message, issue #8.
    optim.zero_grad()
    optim.step()

    for epoch in range(1, 20):
        scheduler_warmup.step(epoch)
        print(epoch, optim.param_groups[0]['lr'])

        optim.step()    # backward pass (update network)


1 0.020000000000000004
2 0.04000000000000001
3 0.06
4 0.08000000000000002
5 0.1
6 0.1
7 0.09045084971874738
8 0.07938926261462366
9 0.06545084971874737
10 0.05
11 0.03454915028125263
12 0.02061073738537635
13 0.009549150281252633
14 0.0024471741852423235
15 0.0
16 0.0024471741852423127
17 0.009549150281252623
18 0.02061073738537634
19 0.034549150281252626
